# Generated by Django 4.1.4 on 2022-12-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('prediction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_deployment.prediction')),
                ('sample', models.ImageField(upload_to='')),
            ],
            bases=('model_deployment.prediction',),
        ),
        migrations.CreateModel(
            name='TextPrediction',
            fields=[
                ('prediction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_deployment.prediction')),
                ('sample', models.TextField()),
            ],
            bases=('model_deployment.prediction',),
        ),
    ]
