# Generated by Django 4.1.4 on 2022-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprediction',
            name='sample',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
